# Generated by Django 3.2.4 on 2021-06-17 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ForgotPassword',
        ),
    ]
